### PR TITLE
Added proper commonjs support

### PR DESCRIPTION
**Pull request by callumacrae**
Right now you're relying on `window.jQuery`. I don't have that global var, so this library wasn't working for me.

### CODE REVIEW

**Comment by kswedberg** [comment]
thanks, @callumacrae !

**Comment by callumacrae** [comment]
Awesome :) would you be able to release 1.5.5 and push to npm so that I can use it?

**Comment by kswedberg** [comment]
you betcha. Just needed to add the commonjs condition to my build template. you should see something within a minute or two.

**Comment by callumacrae** [comment]
Cheers :)

**Pull request closed without merging**
